# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  issues:
    types: [opened, reopened, closed, deleted]
  issue_comment:
    types: [created, deleted]  
#  schedule:
#    - cron: "13 22 * * *"   # <=== One time in a day at 6 PM

#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Upload JAR file
      uses: actions/upload-artifact@v4
      with:
        name: dpm-artifact
        path: target/*.jar

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1.0.0
      with:
          tag_name: v1.0.0
          release_name: Release v1.0.0
          body: 'Release of JAR file.'
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload JAR to Release
      uses: actions/upload-release-assets@v1.1.1
      with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: target/*.jar
          asset_name: DPM.jar
          asset_content_type: application/java-archive
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    #- name: Update dependency graph
    #  uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
